version: "3.8"

services:
  dicomserver:
    image: ${DOCKER_REGISTRY-}microsofthealthdicomweb
  functions:
    image: ${DOCKER_REGISTRY-}microsofthealthdicomfunctions
  azurite:
    # Slightly different ports are used as to not collide with any currently running storage emulator in Visual Studio
    ports:
      - "10001:10011"
      - "10000:10010"
      - "10002:10012"
  sql:
    ports:
      - "1433:1433"
