version: '3.4'

services:
  microsoft.health.dicom.web:
    image: ${DOCKER_REGISTRY-}microsofthealthdicomweb
    build:
      context: ./..
      dockerfile: src/Microsoft.Health.Dicom.Web/Dockerfile
    environment:
      DicomServer__Security__Enabled: "false"
      # [SuppressMessage("Microsoft.Security", "CS002:SecretInNextLine", Justification="Password is only used for development.")]
      SqlServer__ConnectionString: "Server=tcp:sql,1433;Initial Catalog=DICOM;Persist Security Info=False;User ID=sa;Password=T3stP@ssw0rd;MultipleActiveResultSets=False;Connection Timeout=30;"
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__Initialize: "true"
      BlobStore__ConnectionString: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      DataStore: "SqlServer"
    depends_on:
      - sql
      - azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
  sql:
    build:
      context: ./..
      dockerfile: ./build/docker/sql/Dockerfile
    environment:
      # [SuppressMessage("Microsoft.Security", "CS002:SecretInNextLine", Justification="Password is only used for development.")]
      SA_PASSWORD: T3stP@ssw0rd
      ACCEPT_EULA: "Y"
