name: build-docker-files

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  build_docker_files:
    # create a quick build to get sane output and error messages
    runs-on: ubuntu-latest
    steps:
    - 
      bash: |
        set -exo pipefail
        sed -i 's;</packageSources>;</packageSources><packageSourceCredentials><Internalfeed><add key="Username" value="any" /><add key="ClearTextPassword" value="$(System.AccessToken)" /></Internalfeed></packageSourceCredentials>;' nuget.config
      displayName: 'Authenticate additional nuget packages'
    - 
      uses: actions/checkout@v2
    -
      # sample contains all the docker files
      name: Build all docker files
      run: |
        docker-compose build
      working-directory: samples/docker
