name: build-docker-files

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_docker_files:
    # create a quick build to get sane output and error messages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build all docker files
      run: |
        docker-compose build
      working-directory: samples/docker

    - name: Test Docker Sample
      run: .github/workflows/test-docker.ps1
      shell: pwsh
      timeout-minutes: 6
